### ISSUE TITLE
Any TODO list?

### ISSUE THREAD

**Issue by arturluizbr** [kainolophobia/neo4j-livedata#3]
I would like to help in this project.
Do you have some task planned?

**Comment by jessekrasnostein** [comment]
+1

**Comment by dr-dimitru** [comment]
Hi all, and @jessekrasnostein 
As this repository not moving forward, at the end of previous year we've released [Neo4jreactivity package for Meteor](https://github.com/VeliovGroup/ostrio-Neo4jreactivity)

**Comment by kainolophobia** [comment]
Hey guys, 

Sorry I haven't had time for this lately, it's still a project I plan to see through to completion.

The current bottleneck is such: Meteor doesn't have a way to handle complex queries well, as the livedata is collection-based. Graph queries (and SQL joins across multiple tables, for that matter) are the result of connecting many different "collections" and thus cannot be easily observed for changes and can easily be too large to represent on the client. As such, my goal is to implement a query-cache of sorts that will rely on polling. The problem with oplog support also revolves around the inability to handle complex queries (let alone adding an oplog type support to Neo4j). This solution is non-ideal, as it's a "hack" on top of Meteor. I've spoken with the Meteor team, and there's no clear path for handling SQL, let alone graph databases, in the near-term future. Thus, the problem is larger than the scope of this particular repository, but there are things we can do to make working with Neo4j within a Meteor app much easier. 

I'd love to chat with anyone interested in this.

Cheers,
Adam

@dr-dimitru Your solution is interesting, as it's using Mongo for the query cache rather than replacing it with Neo4j altogether. I'm not convinced that proxying everything through Mongo is the right solution for everyone, but it's cool nonetheless and definitely more usable than this project :)
